# Generated by Django 3.2.7 on 2021-09-30 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighhood',
            options={'ordering': ['neighbourhood_name']},
        ),
        migrations.RenameField(
            model_name='neighhood',
            old_name='hoodname',
            new_name='neighbourhood_name',
        ),
        migrations.AlterField(
            model_name='neighhood',
            name='occupantscount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('email_address', models.EmailField(max_length=254)),
                ('Neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoodapp.neighhood')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=150)),
                ('business_emailaddress', models.EmailField(max_length=254)),
                ('Neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoodapp.neighhood')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoodapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='neighhood',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hoodapp.user'),
            preserve_default=False,
        ),
    ]
