# Generated by Django 3.2.7 on 2021-09-30 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0003_auto_20210930_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighhood',
            name='user',
        ),
        migrations.AddField(
            model_name='neighhood',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hoodapp.profile'),
            preserve_default=False,
        ),
    ]
