# Generated by Django 3.2.7 on 2021-09-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0005_alter_neighhood_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighhood',
            name='image',
            field=models.ImageField(default=1, upload_to='hoods/'),
            preserve_default=False,
        ),
    ]
